import React from 'react';
import ReactMarkdown from 'react-markdown';
import { X, Sparkles, Loader2 } from 'lucide-react';

const AITab = ({ problem, suggestion, isLoading, onClose }) => {
    if (!problem && !isLoading && !suggestion) {
        return (
            <div className="ai-sidebar empty-state-container">
                <div className="ai-empty-state">
                    <Sparkles size={48} className="ai-empty-icon" />
                    <h3>AI Assistant</h3>
                    <p>Select "Ask AI" on any issue to get smart suggestions and solutions powered by Gemini.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="ai-sidebar active slide-down">
            <div className="ai-header">
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Sparkles size={20} className="ai-sparkle-icon pulse-button" style={{ color: 'var(--accent-color)', borderRadius: '50%' }} />
                    <h3>AI Suggestions</h3>
                </div>
                {onClose && (
                    <button className="icon-btn" onClick={onClose} title="Close AI Panel">
                        <X size={20} />
                    </button>
                )}
            </div>

            <div className="ai-content-area">
                {problem && (
                    <div className="ai-context-box">
                        <span className="ai-context-label">Analyzing Issue:</span>
                        <h4 className="ai-context-title">{problem.title}</h4>
                    </div>
                )}

                {isLoading ? (
                    <div className="ai-loading-state">
                        <Loader2 size={32} className="spinning-loader" />
                        <p>Gemini is thinking...</p>
                        <span className="loading-subtitle">Analyzing the problem and generating constructive solutions.</span>
                    </div>
                ) : suggestion ? (
                    <div className="ai-markdown-content">
                        <ReactMarkdown>{suggestion}</ReactMarkdown>
                    </div>
                ) : null}
            </div>

            <div className="ai-footer">
                <p>Generated by Google Gemini AI. These are automated suggestions and should be verified.</p>
            </div>
        </div>
    );
};

export default AITab;
